- menu_name: "Tjenester"

- name: "Kontakt"
  url: "/kontakt/"
  title: "Kontaktdetaljer"

- name: "RSS"
  url: "/feed.xml"
  title: "Hold deg oppdatert med RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Hold deg oppdatert med Atom-feed"

#- name: "Sidekart"
#  url: "/sitemap.xml"
#  title: "Sidekart for siden"
